### ISSUE TITLE
Use APOC to better support datetime objects (and more)

### ISSUE THREAD

**Issue by sparklespdx** [lyft/cartography#109]
I saw this comment in the elasticsearch transform:

https://github.com/lyft/cartography/blob/909bb3804b5aab311432351c144ce5654ec551fb/cartography/intel/aws/elasticsearch.py#L94-L95

Neo4J doesn't support datetime natively, but there's an extension set that does:

http://neo4j-contrib.github.io/neo4j-apoc-procedures/3.5/utilities/datetime-conversions/

Would the project consider using this extension pack?

**Comment by achantavy** [comment]
Hi, thanks for pointing this out.  Unfortunately we don't have cycles to investigate this at the moment.  Temporal types in Neo4j were added in a more recent version (we think) and we haven't had a chance to test the newer versions, plus moving to temporal types would need us to use actual datetime objects instead of strings.

**Comment by sparklespdx** [comment]
Thanks for the response! That's very understandable.

I just did a major version upgrade of Neo4J for a very similar project and it went off without a hitch. I am very interested in using Cartography, if I try using APOC in my installation I'll post in this issue.

**Comment by achantavy** [comment]
Thanks!  Interested in hearing how it goes.
