### ISSUE TITLE
Required permissions missing from documentation?

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#212]
Hi,
when deploying Cartography to scan both AWS and GCP, I noticed that the following permissions, although required, are not mentioned in the README:

| CSP  | Permission | Needed for |
| ------  | --------------- | --------------- |
| AWS | `ec2:DescribeRegions` | Cartography will fail without this permission, as it won't be able to fetch all the regions used by the AWS accounts |
| GCP | `roles/resourcemanager.organizationViewer` | Needed to list/get the GCP Organization. Cartography returns an empty list if this permission is not granted |
| GCP | `roles/resourcemanager.folderViewer` | Needed to list/get Folders. Cartography returns an empty list if this permission is not granted, which means no Projects will be analysed |

If you agree on this (unless I'm missing something) I will be happy to create a PR to extend the README.

**Comment by ramonpetgrave64** [comment]
At my organization, it was tricky getting it to fully work across our entire GCP account: I had to grant the service account permissions at the `organization` level. We used a specific set of required permissions, since we felt that  the `SecurityReviwer` role might have been overly permissive. 

But I agree that the docs could specify which predefined roles are needed to `list` orgs, folders, projects, instances, etc.

**Comment by achantavy** [comment]
> If you agree on this (unless I'm missing something) I will be happy to create a PR to extend the README.

@marco-lancini Please do so! :-)

> But I agree that the docs could specify which predefined roles are needed to list orgs, folders, projects, instances, etc.

@ramonpetgrave64 For sure.

**Comment by marco-lancini** [comment]
A first draft is now on PR #213
