### ISSUE TITLE
Automatically identify new accounts/projects

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#265]
*Title*: I'd like to extend Cartography so to provide automatic detection of new AWS accounts/GCP projects

*Description*:
Cartography is usually setup to scan all AWS accounts and all GCP projects within an organization. Hence, it can be extended so to leverage its drift detection capabilities to notify whenever a new AWS account or GCP project appears.

* AWS: we can leverage the [list_accounts](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#Organizations.Client.list_accounts) method to obtain a list of accounts within the organization
* GCP: we can leverage [gcloud projects list](https://cloud.google.com/sdk/gcloud/reference/projects/list) to do the same

The main question would be where is the best place to run this collection: as a new analysis job/intel module/or?

It is worth noting this feature can be useful as it will extend the use cases for Cartography: this will allow to use Cartography as an independent, complementary, solution to Terraform drift detection (for cases of accounts not managed by TF, and/or as an additional verification).

Any comments/ideas/objections?

**Comment by achantavy** [comment]
We experimented with this and it is possible but tricky. I will share the code that we used - I think this is a cool project if we can do it right but there are a few nuances.

This process takes the following steps:

1. Use the organizations API to get all accounts accessible by the current set of AWS creds
1. Create the boto3_* objects dynamically so that we are able to access assets in these accounts
1. Access the accounts

To get step 2 working, we created a subclass of `botocore.session.Session` that allowed us to set the desired AWS accounts in memory by overriding [`Session.full_config`](https://github.com/boto/botocore/blob/68a20a9153af0a15ef67db41222dc8c4ca51274b/botocore/session.py#L342). This was necessary because the vanilla boto3 interfaces don't allow you to specify this in memory; as far as we could tell, you are forced to read from the config file on disk. Although this worked, our implementation made assumptions about the `credential_sources` and other fields. An alternate way to do this would be to write to ~/.aws/config on the filesystem, but this isn't a good option as it thrashes a user's config.

Also, many workplaces don't have all accounts available in an organization object (as much as they should!), so we would need to support both automated account discovery as well as the current flow of deferring to boto3 as much as possible.

**Comment by marco-lancini** [comment]
Hi @achantavy, thank you for providing these details!
I think we can tackle this with incremental steps: for me, even step 1 would already be super-beneficial to detect new accounts that might have been created accidentally and/or outside the approved creation process (which includes a step to onboard them into Cartography).
I also see the challenges in addressing points 2 and 3, so I'd like to start tackling 1 first.

I did a quick smoke test, by adding a short snippet of code in the `_sync_multiple_accounts` function (https://github.com/lyft/cartography/blob/master/cartography/intel/aws/__init__.py#L64). Just after initializing the boto3 session, and before jumping into `_sync_one_account`, we could check if the current account has permissions to list the org. Ideally, only one account should be the `root` one, with necessary permissions to perform:
```
org = boto3_session.client('organizations')
response = org.list_accounts()
``` 
If you are ok with this approach, I'll extend this by adding the results from the snippet above to the graph, and I'll formalise a PR.

**Comment by achantavy** [comment]
@marco-lancini Just to make sure I understand, the idea is:

1. Use the current credentials to call `organizations.list_accounts()`
2. Load the accounts returned from step 1 as :AWSAccount nodes
3. Finally, if step 1 yields more accounts than what is configured in our current AWS context, don't bother syncing the contents of those accounts

Put another way, suppose our AWS config file is configured to access accounts A, B, C. We call `organizations.list_accounts()` and it returns `[A, B, C, D]`. Account D is not present in our AWS config file, so although we will create a new `:AWSAccount` node for it, we will not sync its contents.

If this is your idea, I think it's solid.

**Comment by marco-lancini** [comment]
Correct! You did explain it waaay better than me :D
