### ISSUE TITLE
Map Lambda function to the role it uses

### ISSUE THREAD

**Issue by eRaMvn** [lyft/cartography#309]
**Feature request template**

*Title*: Map Lambda function to the role it uses

*Description*:
> Describe your idea.  Please be detailed.  If a feature request, please
describe the desired behavior, what scenario it enables, and how it
would be used.

I don't see lambda function as one of the services supported by this project. I think it would be really helpful to see what roles/permissions the lambda function has access to in cases the attacker can gain access to invoke a lambda 

Also, even when the map was created, in the metadata of the role, is it possible that we can put in the IAM role policy to show in neo4j instead of just the name of the role. That way we dont have to go back and forth between the database and the actual account to check for permissions

Pseudo code would be something like this:

```
for each lambda:
    create_mapping("(lambda)-->(role)")

for each statement in eachh role:
    if lambda:Invoke in the policy:
        create_mapping("(role)-->(lambda)")
```

I can help and it looks like I will just need add a new file for lambda service under intel/aws right. How do I add the policy of the role/iam user to the metadata. I am not familiar with the query language of neo4j so I would have to learn that

Thank you for this great project

**Comment by achantavy** [comment]
Hey @eRaMvn, thanks very much for proposing this and offering to add this feature. I agree - having Lambdas would be really great.

> Also, even when the map was created, in the metadata of the role, is it possible that we can put in the IAM role policy to show in neo4j instead of just the name of the role. 

You have the right idea. @SecPrez did some great work on evaluating IAM policies so that [roles are mapped to different assets](https://docs.google.com/document/d/12N5Jf3DbCVo7d84fV7iJshLK6bGRoQl1nOe4Dynd2JE/edit#heading=h.kkbojcj7qpvj) in [this PR](https://github.com/lyft/cartography/pull/283). It would be very straightforward for you to add a mapping from AWS roles to lambda functions. To make this happen, you would only need to edit https://github.com/lyft/cartography/blob/master/cartography/data/permission_relationships.yaml with something like 

```
- target_label: AWSLambda
  permissions:
  - lambda:InvokeFunction
  relationship_name: CAN_EXECUTE
```
and our [permission relationships code](https://github.com/lyft/cartography/blob/master/cartography/intel/aws/permission_relationships.py) will automatically make that mapping for you.

As for including the actual policy... hm, we might need to make some changes, let's talk on that more.

As a side note I hope that you find our [developer guide](https://github.com/lyft/cartography/blob/master/docs/dev/developer-guide.md) and our [how to make an intel module guide](https://github.com/lyft/cartography/blob/master/docs/dev/writing-intel-modules.md) helpful.

Please say hi in Slack too!

**Comment by eRaMvn** [comment]
Thank you @achantavy  for your response. That is so interesting. I can see the policies attached to a role and the statements within each policy, but I was just wondering if it would be helpful to have a field under AWSRole or AWSPrincipal entity that is called Permissions or something (besides the existing ones like roleid, arn, etc.). I dont know if this is possible in Neo4j but the Permission field can be a string like this
"[
  {Policy 1
    {Statement 1}
    {Statement 2}
  }
  {Policy 2
    {Statement 1}
    {Statement 2}
  }
]"

**Comment by achantavy** [comment]
Since we already have the `(:AWSPrincipal:AWSRole)-->(:AWSPolicy)-->(:AWSStatement)` path in the graph, I don't think we should include statement information on the role/principal node because that'd be keeping redundant data in two different places and Neo4j isn't the best at keeping lists on node fields (there _are_ places where we keep lists on nodes but I don't think it fits here). To get that statement permissions data, I'd recommend querying for that above path that I described.

I'm open to other opinions though!

**Comment by eRaMvn** [comment]
Hi @achantavy, I was browsing through the code earlier today. Let's say I have a list of lambda functions and I know what role is attached to each lambda. How do I make connection my each lambda entity to the iam entity to create a relationship (lambda)-[a:AssumeRole]->(iam_role). I looked through each module under intel/aws but not sure how make the connection between the two entities

Also, in each module, I can see a function called cleanup and it takes an argument of a json file such as "'aws_import_s3_buckets_cleanup.json' or 'aws_import_rds_instances_cleanup.json'. How did those files get created in the first place? What is in those files?

Thank you and apologies for questions that showed I lacked an understanding of neo4j

**Comment by achantavy** [comment]
> How do I make connection between each lambda entity and the iam role entity to create a relationship like (lambda)-[a:AssumeRole]->(iam_role)

I would recommend putting your call to the lambda sync [here](https://github.com/lyft/cartography/blob/d339848bcc5bc301a91041cd86992b8cf3c09da4/cartography/intel/aws/__init__.py#L45), and then your query to make that link will look like

```
// First find the role that was loaded in iam.py
MATCH (role:AWSPrincipal{arn:<ARN goes here>})

// Now create your lambda node
MERGE (lambda:AWSLambda) 
// Fill out fields that will never change
ON CREATE SET lambda.id = {the arn}, 
lambda.arn = {the arn},
lambda.firstseen = {update_tag}
// Fill out fields that may change
SET lambda.field1 = value1,
lambda.field2 = value2,
... etc ...
lambda.fieldN = valueN,
lambda.lastupdated = {update_tag}

// Now connect them together
MERGE (lambda)-[r:STS_ASSUME_ROLE_ALLOW]->(role)
// Fill out fields that will never change on the relationship
ON CREATE SET r.firstseen = {update_tag}
// Fill out fields that may change 
SET r.lastupdated = {update_tag}
```

> Also, in each module, I can see a function called cleanup and it takes an argument of a json file such as "'aws_import_s3_buckets_cleanup.json' or 'aws_import_rds_instances_cleanup.json'. How did those files get created in the first place?

We have to write these manually.

> What is in those files?

See [here](https://github.com/lyft/cartography/blob/master/docs/dev/writing-intel-modules.md#cleanup) :-). The idea is to delete nodes and relationships that don't exist anymore. This way you can run `cartography` on a cronjob so that you'll have the most up-to-date view on your infra available.

**Comment by eRaMvn** [comment]
@achantavy thank you! Your comment helped me a lot. I created a PR after testing on my account. Can you please review and provide any feedback? I am not too positive about the query to clean up

**Comment by achantavy** [comment]
Added in #334 !
