### ISSUE TITLE
ECRRepository is storing ECRRepositoryImage data, rather than ECR-related ones

### ISSUE THREAD

**Issue by marco-lancini** [lyft/cartography#473]
Upon running Cartography 0.29.1, and ingesting ECR data for the first time I can see that `ECRRepository` is not actually carrying ECR-related info, but it is actually representing specific images.

The query below returns the full list of images within the repo, rather than info of the repo itself:

```
MATCH (a:AWSAccount)-[:RESOURCE]->(r:ECRRepository) RETURN a.name, r.name, r.region, r.uri
```

The following query (which should return a list of images), returns empty:
```
MATCH (a:AWSAccount)-[:RESOURCE]->(r:ECRRepository)-[:REPO_IMAGE]->(i:ECRRepositoryImage) RETURN * 
```

**Comment by marco-lancini** [comment]
Paging @ngowraj

**Comment by achantavy** [comment]
That seems really really odd; it confuses me that [this test](https://github.com/lyft/cartography/blob/0d82bf67b5c3754b31ee7e5e2e026d43a8ddb3a5/tests/integration/cartography/intel/aws/test_ecr.py#L64-L83) still passes. You might want to manually delete these bad nodes and try again using the latest master since I removed the slower running image scan findings code. If needed I'll release a 0.29.2.

**Comment by marco-lancini** [comment]
Ok, apparently a case of stale data. Resolved
