### ISSUE TITLE
Sync frequency config?

### ISSUE THREAD

**Issue by steve-solun** [lyft/cartography#896]
Is there a way to schedule and manage the update rate of cartography against my cloud, @achantavy?

**Comment by achantavy** [comment]
Hi @steve-solun, can you provide more details on what you've considered so far?

We briefly mention this here: https://lyft.github.io/cartography/ops.html#sync-frequency

> To keep data updated, you can run cartography as part of a periodic script (cronjobs in Linux, scheduled tasks in Windows). Determine your needs for data freshness and adjust accordingly.

Since cartography is just a CLI tool, you can have it run in a cronjob and define how frequently you want it to run. It's also possible to write [custom sync scripts](https://lyft.github.io/cartography/dev/developer-guide.html#implementing-custom-sync-commands) where you write your own python code and import cartography libraries. If you wanted to get fancy you could wire that up to something like Airflow for DAGs.

**Comment by steve-solun** [comment]
Thank you @achantavy

**Comment by achantavy** [comment]
👍
